DROP TABLE IF EXISTS users

CREATE TABLE IF NOT EXISTS users (
    id int generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(512) not null unique,
    age smallint not null,
    created_at timestamp without time zone
);